export default function DemoFooter({ business, accent, bg, muted = "#9AA1AB" }) {
  return (
    <footer className="px-6 md:px-12 py-10 text-center border-t" style={{ borderColor: `${accent}22` }}>
      <p className="text-xs" style={{ color: muted }}>
        {business} — demo site generated by LeadForge AI. Not the business's live website.
      </p>
    </footer>
  );
}
